version: "3.9"
services:
  cons-app:
    build: ./
    image: cons-img
    ports:
      - "3001:3000"
      - "6007:6006"
    working_dir: /cons-app/ui
    command: bash -c "nohup yarn start & yarn storybook"
    volumes:
      - cons-ui:/cons-app/ui
    networks:
      - cons

networks:
  cons:
    driver: bridge

volumes:
  cons-ui:
